### ISSUE TITLE
unix-sandbox-in-windows_install.hta:981 line issue

### ISSUE THREAD

**Issue by HuangShumin** [ildar-shaimordanov/jsxt#2]
for /f "skip=4 tokens=1,2,*" %%a in ( 'reg query %uninstall_reg% /v "%SANDBOX_DISK%"' ) do (

this should be only skipped 2 lines, so fix it by change skip=4 to skip=2:

for /f "skip=2 tokens=1,2,*" %%a in ( 'reg query %uninstall_reg% /v "%SANDBOX_DISK%"' ) do (

**Comment by ildar-shaimordanov** [comment]
Hi @HuangShumin 

Thank you for interest to this project. To be honest, this script is very old. If you're interested in a such kind of functionality, I would like to suggest you to try `fsbox.bat` from https://github.com/ildar-shaimordanov/cmd.scripts, the CLI tool doing the same stuff.

Nevertheless, I've fixed the current issue by the commit b69d8c5.
