### ISSUE TITLE
FileSystem.js:17

### ISSUE THREAD

**Issue by HuangShumin** [ildar-shaimordanov/jsxt#3]
WScript can only be available by wscript/cscript.exe, non exists in browser/HTA.

Fix it by:
FileSystem.fileName = typeof WScript != undefined || WScript.ScriptName;

FileSystem.fullName = typeof WScript != undefined || WScript.ScriptFullName;

FileSystem.dirName = typeof WScript != undefined || FileSystem.fullName.replace(/\\[^\\]+$/, '');

**Comment by ildar-shaimordanov** [comment]
Fixed in commit 99ad3b0
